version: "3.8"
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: loterias_admin
      MONGO_INITDB_ROOT_PASSWORD: loterias_admin_1234
    ports:
      - "27017:27017"
    command: mongod --bind_ip 0.0.0.0

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: loterias_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: loterias_admin_1234
      ME_CONFIG_MONGODB_URL: mongodb://loterias_admin:loterias_admin_1234@mongodb:27017/

  seeders:
    build: ./seeders
    depends_on:
      - mongodb
  
  prometheus:
    image: prom/prometheus:latest
    user: root
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    #network_mode: host
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9090:9090
    networks:
      - probabilidade-network
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    environment:
      -  GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - probabilidade-network
      
volumes:
  prometheus_data: {}
networks:
  probabilidade-network:
    driver: bridge

