{
 "title": "Probabilidade",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "HTTP_STATUS_CODE",
    "label": "Status Code",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket, code)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Prometheus Default", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Probabilidade API",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "healthcheck{healthcheck=\"self\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória de Processamento",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "healthcheck{healthcheck=\"process_memory\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória Privada",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "healthcheck{healthcheck=\"private_memory\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDb",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "healthcheck{healthcheck=\"mongodb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests em progresso",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_in_progress)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uso da CPU pelo serviço ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_percentage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memória usada em GB",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_working_set_bytes / (1024 * 1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória virtual usada em GB",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "memory_virtual_set_bytes / (1024 * 1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests / Segundo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total[1m])*60",
     "legendFormat": "{{endpoint}} - {{code}}"
    }
   ]
  },
  {
   "title": "Requisições",
   "type": "stat",
   "gridPos": { "h": 14, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests / Segundo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"$HTTP_STATUS_CODE\"}[1m]))",
     "legendFormat": "HTTP - $HTTP_STATUS_CODE"
    }
   ]
  },
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 7, "w": 4, "x": 20, "y": 27 } },
  {
   "title": "Taxa de erro",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{code=~\"^4.*|^5.*\"}[1m])) / sum(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Erro Requests"
    }
   ]
  },
  {
   "title": "Percentil tempo de reposta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket[1m])) by(le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de reposta p50 - p90 - p95 - p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket[1m])) by(le))",
     "legendFormat": "p 0.50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket[1m])) by(le))",
     "legendFormat": "p 0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by(le))",
     "legendFormat": "p 0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[1m])) by(le))",
     "legendFormat": "p 0.99"
    }
   ]
  },
  {
   "title": "OpenTelemetry Prometheus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests / Segundo",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "rate(http_server_request_duration_seconds_count[1m])*60",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(rate(http_server_request_duration_seconds_count[1m]))*60",
       "legendFormat": "Total Request"
      }
     ]
    },
    {
     "title": "Percentil tempo de reposta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "sum(rate(http_server_request_duration_seconds_bucket[1m])) by(le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Tempo de reposta p95 - p90 - p50",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket[1m])) by(le))",
       "legendFormat": "p 0.95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket[1m])) by(le))",
       "legendFormat": "p 0.90"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_server_request_duration_seconds_bucket[1m])) by(le))",
       "legendFormat": "p 0.5"
      }
     ]
    }
   ]
  }
 ]
}